export const GET_SUMMARY = "GET_SUMMARY";
export const SUBMIT_VACXIN = "SUBMIT_VACXIN";
export const SUBMIT_DECLARATION = "SUBMIT_DECLARATION";
export const SUBMIT_DECLARATION_LOADING = "SUBMIT_DECLARATION_LOADING";
export const SUBMIT_VACXIN_LOADING = "SUBMIT_VACXIN_LOADING";
